[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "foxus"
authors = [{name = "Zelle Marcovicci", email = "zelle@foxus.com"}]
dynamic = ["version", "description"]
